### ISSUE TITLE
Weird scss

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/okturtles.org#33]
A few issues here:

``` scss
.clearfix { display: inline-block; }
/* start commented backslash hack \*/
* html .clearfix { height: 1%; }
.clearfix { display: block; }
/* close commented backslash hack */
.clearfix:after {
  visibility: hidden;
  display: block;
  font-size: 0;
  content: " ";
  clear: both;
  height: 0;
}
```
- `.clearfix` is defined twice for some reason, with different values
- Not clear what the "backslash hack" is
- What on earth is `* html .clearfix { height: 1%; }` ?
##
